import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main style={{ flex: 1 }}>{children}</main>
        <footer style={{
          borderTop: "1px solid var(--surface-border)",
          padding: "20px",
          textAlign: "center",
          fontSize: "0.8rem",
          color: "var(--text-secondary)",
          background: "rgba(15, 17, 26, 0.8)",
          backdropFilter: "blur(8px)",
          marginTop: "auto"
        }}>
          <div style={{ display: "flex", gap: "20px", justifyContent: "center", marginBottom: "8px" }}>
            <a href="/privacy" style={{ color: "var(--text-secondary)", textDecoration: "none" }}>Privacy Policy</a>
            <span>•</span>
            <a href="/terms" style={{ color: "var(--text-secondary)", textDecoration: "none" }}>Terms of Service</a>
            <span>•</span>
            <a href="mailto:thegeiya@gmail.com" style={{ color: "var(--text-secondary)", textDecoration: "none" }}>Support</a>
          </div>
          <div>© 2026 Hillary Njuguna • Agent Trust Readiness Suite</div>
        </footer>
      </body>
    </html>
  );
}
