import React from "react";
import Link from "next/link";

export default function TermsOfServicePage() {
  return (
    <div className="container" style={{ padding: "40px", maxWidth: "800px", margin: "0 auto" }}>
      <div className="glass-panel">
        <h1 style={{ fontSize: "1.8rem", marginBottom: "10px", color: "#fff" }}>Terms of Service</h1>
        <p style={{ color: "var(--text-secondary)", fontSize: "0.85rem", marginBottom: "25px" }}>
          Last updated: August 7, 2026
        </p>

        <section style={{ marginBottom: "20px", color: "var(--text-primary)", lineHeight: "1.6", fontSize: "0.9rem" }}>
          <h2 style={{ fontSize: "1.2rem", color: "var(--accent-color)", marginTop: "20px" }}>1. Scope of Diagnostic Evaluation</h2>
          <p>
            The Agent Trust Readiness Diagnostic provides an informational, self-assessed evaluation framework for AI agent workflows. It is intended for internal readiness preparation and pre-diligence governance review.
          </p>
        </section>

        <section style={{ marginBottom: "20px", color: "var(--text-primary)", lineHeight: "1.6", fontSize: "0.9rem" }}>
          <h2 style={{ fontSize: "1.2rem", color: "var(--accent-color)", marginTop: "20px" }}>2. Disclaimer of Legal & Compliance Guarantee</h2>
          <p>
            Reports and scores generated by this tool do not constitute formal legal, financial, accounting, or regulatory advice. Passing or satisfying diagnostic gates does not guarantee third-party approval by payment processors, underwriters, enterprise clients, or regulatory authorities.
          </p>
        </section>

        <section style={{ marginBottom: "20px", color: "var(--text-primary)", lineHeight: "1.6", fontSize: "0.9rem" }}>
          <h2 style={{ fontSize: "1.2rem", color: "var(--accent-color)", marginTop: "20px" }}>3. Products & Fulfillment</h2>
          <p>
            Purchases made via Gumroad (Agent Trust Readiness Report & Founder Trust Review) are subject to manual or automated fulfillment within 12 business hours of purchase receipt.
          </p>
        </section>

        <div style={{ marginTop: "30px", paddingTop: "20px", borderTop: "1px solid var(--surface-border)" }}>
          <Link href="/" className="cta-btn cta-btn-outline" style={{ display: "inline-block", width: "auto" }}>
            Return to Diagnostic
          </Link>
        </div>
      </div>
    </div>
  );
}
